2015-04-07 17:42:13,415 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-07 17:46:55,834 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-09 20:59:20,514 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-09 21:06:05,837 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-09 21:06:26,399 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-09 21:23:06,949 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-09 21:23:52,621 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-09 21:25:10,818 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-09 21:34:15,312 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-09 21:34:39,282 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-09 21:37:13,334 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-09 21:37:45,648 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-09 21:38:40,737 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-09 21:39:08,980 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 00:23:35,030 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 00:23:49,595 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 00:28:38,840 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 00:30:54,468 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 00:31:05,040 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 00:31:10,540 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 00:31:41,431 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 00:31:49,332 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 00:33:09,539 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 00:33:17,959 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 00:34:54,369 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 00:35:03,463 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 00:35:10,324 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 01:06:57,498 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 01:11:20,401 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 01:12:11,910 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 10:13:02,802 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 10:14:49,291 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 10:30:02,640 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 10:31:16,277 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 19:32:02,512 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 19:36:20,213 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 19:38:42,962 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-10 20:01:23,120 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 20:18:38,299 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 20:19:11,202 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 20:20:22,994 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 20:23:35,489 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 20:26:18,895 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 20:27:14,236 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 20:28:32,083 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 20:44:37,492 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 20:44:37,704 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 20:45:21,265 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 20:45:33,586 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 20:58:19,051 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 21:00:44,386 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 21:02:27,460 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 21:03:37,264 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 21:11:06,282 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-10 21:15:10,519 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-11 00:03:09,362 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-11 00:03:09,552 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-11 00:12:31,239 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-11 00:56:40,095 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-12 21:31:26,244 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 10:17:04,960 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 10:24:52,840 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 10:25:49,175 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 10:27:36,182 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 10:29:13,165 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 10:30:01,664 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 10:31:52,732 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 10:32:42,009 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 10:33:35,158 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 10:34:18,357 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 10:35:37,977 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 10:36:51,875 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 10:37:47,505 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 10:41:36,257 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 10:42:29,795 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 10:43:47,988 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 10:44:56,988 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 10:46:08,648 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 10:47:10,042 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 10:47:50,042 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 10:48:57,448 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 10:59:54,862 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 11:04:47,348 INFO: savbu-inventory startup [in app/__init__.py:42]
2015-04-13 12:23:15,123 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-13 12:23:15,407 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-13 12:24:03,048 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-13 12:25:03,817 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-13 12:25:20,226 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-13 12:34:05,558 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-13 12:47:57,447 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-13 12:48:06,796 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-13 12:53:12,463 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-13 12:53:12,753 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-13 12:53:37,220 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-13 12:55:09,209 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-13 12:55:59,867 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-13 12:56:57,604 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-13 13:07:51,474 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-13 13:07:51,705 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-13 23:45:56,760 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-13 23:45:56,983 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-13 23:54:29,495 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-13 23:55:43,381 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-13 23:57:13,371 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-13 23:57:16,647 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-13 23:57:43,134 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 00:10:50,597 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 00:10:50,860 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 00:18:56,259 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 00:18:56,529 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 00:37:04,554 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 00:37:04,781 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 01:07:24,029 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 01:10:01,602 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 10:54:18,435 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 10:56:21,624 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 10:58:33,410 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 10:58:33,669 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 11:01:56,582 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 11:37:33,870 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 11:37:52,293 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 11:51:54,279 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 11:56:00,511 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 11:56:55,207 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 11:57:00,508 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 11:57:12,901 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 11:57:26,301 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 17:17:39,397 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 17:17:39,625 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 17:28:20,111 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 17:29:26,910 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 17:32:13,507 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 17:51:11,887 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 17:53:02,018 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 17:53:26,470 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 17:53:30,745 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 17:56:38,504 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 18:05:03,784 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 18:05:47,380 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 18:24:25,503 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 18:24:25,726 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 18:25:33,514 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 18:33:28,631 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 18:37:20,367 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 18:37:20,613 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 18:38:31,422 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 18:43:59,332 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 18:44:59,176 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 18:45:18,604 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 18:52:53,651 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 22:02:36,183 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 22:02:36,378 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-14 22:04:23,565 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-15 14:01:15,938 ERROR: Exception on /add_part [POST] [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/views.py", line 123, in add_part
    return render_template('add_part.html', form=form, parts=parts, project_names=project_names, requestors=requestors,
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 554, in compile
    self.handle_exception(exc_info, source_hint=source)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/templates/add_part.html", line 41, in template
    {% if form.PO).errors %}
TemplateSyntaxError: unexpected ')'
2015-04-15 14:01:25,544 ERROR: Exception on /add_part [GET] [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/views.py", line 123, in add_part
    return render_template('add_part.html', form=form, parts=parts, project_names=project_names, requestors=requestors,
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 554, in compile
    self.handle_exception(exc_info, source_hint=source)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/templates/add_part.html", line 41, in template
    {% if form.PO).errors %}
TemplateSyntaxError: unexpected ')'
2015-04-15 14:01:30,606 ERROR: Exception on /add_part [GET] [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/views.py", line 123, in add_part
    return render_template('add_part.html', form=form, parts=parts, project_names=project_names, requestors=requestors,
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 554, in compile
    self.handle_exception(exc_info, source_hint=source)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/templates/add_part.html", line 41, in template
    {% if form.PO).errors %}
TemplateSyntaxError: unexpected ')'
2015-04-15 14:01:41,070 ERROR: Exception on /add_part [GET] [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/views.py", line 123, in add_part
    return render_template('add_part.html', form=form, parts=parts, project_names=project_names, requestors=requestors,
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 554, in compile
    self.handle_exception(exc_info, source_hint=source)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/templates/add_part.html", line 41, in template
    {% if form.PO).errors %}
TemplateSyntaxError: unexpected ')'
2015-04-15 14:02:18,160 ERROR: Exception on /add_part [GET] [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/views.py", line 123, in add_part
    return render_template('add_part.html', form=form, parts=parts, project_names=project_names, requestors=requestors,
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 554, in compile
    self.handle_exception(exc_info, source_hint=source)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/templates/add_part.html", line 41, in template
    {% if form.PO).errors %}
TemplateSyntaxError: unexpected ')'
2015-04-15 14:03:15,100 ERROR: Exception on /add_part [GET] [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/views.py", line 123, in add_part
    suppliers=suppliers, supplier_contacts=supplier_contacts, item_descriptions=item_descriptions)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 554, in compile
    self.handle_exception(exc_info, source_hint=source)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/templates/add_part.html", line 41, in template
    {% if form.PO).errors %}
TemplateSyntaxError: unexpected ')'
2015-04-15 21:53:31,119 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-15 22:21:23,904 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-15 22:21:28,346 ERROR: Exception on /add_part [GET] [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/views.py", line 99, in add_part
    form.status.choices = [(1, 'Available'), (2, 'Unavailable')]
AttributeError: 'AddPart' object has no attribute 'status'
2015-04-15 22:21:34,931 ERROR: Exception on /add_part [GET] [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/views.py", line 99, in add_part
    form.status.choices = [(1, 'Available'), (2, 'Unavailable')]
AttributeError: 'AddPart' object has no attribute 'status'
2015-04-15 22:22:50,127 ERROR: Exception on /add_part [GET] [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/views.py", line 99, in add_part
    form.status.choices = [(1, 'Available'), (2, 'Unavailable')]
AttributeError: 'AddPart' object has no attribute 'status'
2015-04-15 22:23:26,080 ERROR: Exception on /add_part [GET] [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/views.py", line 99, in add_part
    form.status.choices = [(1, 'Available'), (2, 'Unavailable')]
AttributeError: 'AddPart' object has no attribute 'status'
2015-04-15 22:25:01,404 ERROR: Exception on /add_part [GET] [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/views.py", line 99, in add_part
    #form.status.choices = [(1, 'Available'), (2, 'Unavailable')]
AttributeError: 'AddPart' object has no attribute 'status'
2015-04-15 22:25:34,566 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-16 08:31:13,471 ERROR: Exception on /add_part [GET] [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/views.py", line 123, in add_part
    suppliers=suppliers, supplier_contacts=supplier_contacts, item_descriptions=item_descriptions)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/templates/add_part.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/templates/layout.html", line 25, in top-level template code
    {% block body %}{% endblock %}
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/templates/add_part.html", line 172, in block "body"
    {{ form.submit_date(placeholder="Submit Date") }}
UndefinedError: 'app.forms.AddPart object' has no attribute 'submit_date'
2015-04-16 08:32:18,822 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-16 12:08:46,381 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-16 12:08:54,656 ERROR: Exception on /add_part [GET] [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/views.py", line 99, in add_part
    form.status.choices = [(1, 'Available'), (2, 'Unavailable')]
AttributeError: 'AddPart' object has no attribute 'status'
2015-04-16 12:09:35,078 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-16 12:15:04,842 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-16 12:17:00,602 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-16 12:21:14,584 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-16 12:28:41,112 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-16 12:30:36,536 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-16 14:32:00,983 ERROR: Exception on /add_part [GET] [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/views.py", line 123, in add_part
    suppliers=suppliers, supplier_contacts=supplier_contacts, item_descriptions=item_descriptions)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/templates/add_part.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/templates/layout.html", line 25, in top-level template code
    {% block body %}{% endblock %}
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/templates/add_part.html", line 176, in block "body"
    {{ form.submit_date(placeholder="Submit Date") }}
UndefinedError: 'app.forms.AddPart object' has no attribute 'submit_date'
2015-04-16 14:32:15,755 ERROR: Exception on /add_part [GET] [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/views.py", line 123, in add_part
    suppliers=suppliers, supplier_contacts=supplier_contacts, item_descriptions=item_descriptions)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/templates/add_part.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/templates/layout.html", line 25, in top-level template code
    {% block body %}{% endblock %}
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/templates/add_part.html", line 176, in block "body"
    {{ form.submit_date(placeholder="Submit Date") }}
UndefinedError: 'app.forms.AddPart object' has no attribute 'submit_date'
2015-04-16 14:33:21,076 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-16 17:02:51,561 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-16 17:06:50,764 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-16 17:09:48,163 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-16 17:20:06,458 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-16 17:20:13,274 ERROR: Exception on /add_part [GET] [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/views.py", line 98, in add_part
    form = AddPart(request.form)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 96, in __init__
    *args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/wtforms/ext/csrf/form.py", line 21, in __init__
    super(SecureForm, self).__init__(formdata, obj, prefix, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/wtforms/form.py", line 272, in __init__
    super(Form, self).__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/wtforms/form.py", line 52, in __init__
    field = meta.bind_field(self, unbound_field, options)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/wtforms/meta.py", line 27, in bind_field
    return unbound_field.bind(form=form, **options)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/wtforms/fields/core.py", line 346, in bind
    return self.field_class(*self.args, **kw)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/wtforms/fields/core.py", line 744, in __init__
    super(DateField, self).__init__(label, validators, format, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/wtforms/fields/core.py", line 720, in __init__
    super(DateTimeField, self).__init__(label, validators, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'display_format'
2015-04-16 17:28:43,990 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-16 17:29:20,942 ERROR: Exception on /add_part [POST] [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/views.py", line 121, in add_part
    db.session.commit()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 788, in commit
    self.transaction.commit()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 384, in commit
    self._prepare_impl()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 364, in _prepare_impl
    self.session.flush()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1985, in flush
    self._flush(objects)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2103, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2067, in _flush
    flush_context.execute()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 602, in _emit_insert_statements
    execute(statement, params)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 841, in execute
    return meth(self, multiparams, params)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 938, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1070, in _execute_context
    context)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1271, in _handle_dbapi_exception
    exc_info
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1063, in _execute_context
    context)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
InterfaceError: (InterfaceError) Error binding parameter 11 - probably unsupported type. u'INSERT INTO parts ("PO", "PR", part, project_name, requestor, supplier, supplier_contact, item_description, "CPN", "PID", manufacturer_part_num, submit_date, tracking, status, checkout_date, return_date, times_used, current_user, current_project) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' (u'3405987', u'520985370', u'502983750', u'9283750298', u'7502983750', u'2357092875', u'2039587', u'2039857', u'20983572', u'0985273509', u'823750', [u'04/17/2015'], u'928375', u'Unavailable', None, None, 0, None, None)
2015-04-16 17:30:15,790 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-16 17:31:12,869 ERROR: Exception on /add_part [POST] [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/views.py", line 121, in add_part
    db.session.commit()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 788, in commit
    self.transaction.commit()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 384, in commit
    self._prepare_impl()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 364, in _prepare_impl
    self.session.flush()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1985, in flush
    self._flush(objects)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2103, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2067, in _flush
    flush_context.execute()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 602, in _emit_insert_statements
    execute(statement, params)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 841, in execute
    return meth(self, multiparams, params)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 938, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1070, in _execute_context
    context)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1271, in _handle_dbapi_exception
    exc_info
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1063, in _execute_context
    context)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
InterfaceError: (InterfaceError) Error binding parameter 11 - probably unsupported type. u'INSERT INTO parts ("PO", "PR", part, project_name, requestor, supplier, supplier_contact, item_description, "CPN", "PID", manufacturer_part_num, submit_date, tracking, status, checkout_date, return_date, times_used, current_user, current_project) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' (u'458585', u'58458', u'DIMMs', u'FEIUBFA', u'eduaalva', u'HYNIX', u"'Roy Han' <roy.han@us.skhynix.com>", u'HMA42GR7MFR4N\xc3\x83\xc2\xa2\xc3\x82\xc2\x88\xc3\x82\xc2\x92 TFT1       16GB', u'OEINROEI', u'240952', u'FEOIFN2495', [u'04/16/2015'], u'2048572098', u'Available', None, None, 0, None, None)
2015-04-16 17:33:09,069 ERROR: Exception on /add_part [POST] [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/views.py", line 121, in add_part
    db.session.commit()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 788, in commit
    self.transaction.commit()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 384, in commit
    self._prepare_impl()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 364, in _prepare_impl
    self.session.flush()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1985, in flush
    self._flush(objects)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2103, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2067, in _flush
    flush_context.execute()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 602, in _emit_insert_statements
    execute(statement, params)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 841, in execute
    return meth(self, multiparams, params)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 938, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1070, in _execute_context
    context)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1271, in _handle_dbapi_exception
    exc_info
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1063, in _execute_context
    context)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
InterfaceError: (InterfaceError) Error binding parameter 11 - probably unsupported type. u'INSERT INTO parts ("PO", "PR", part, project_name, requestor, supplier, supplier_contact, item_description, "CPN", "PID", manufacturer_part_num, submit_date, tracking, status, checkout_date, return_date, times_used, current_user, current_project) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' (u'25987', u'245', u'dimm', u'Candlestick', u'eduaalva', u'HYNIX', u"'Roy Han' <roy.han@us.skhynix.com>", u'HMA41GR7MFR4N\xe2\x88\x92TFT1         8GB', u'FENOIN', u'239847', u'zEEFOI2307', [u'04/17/2015'], u'25020598', u'Unavailable', None, None, 0, None, None)
2015-04-16 17:33:21,672 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
2015-04-16 17:34:18,146 ERROR: Exception on /add_part [POST] [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/views.py", line 121, in add_part
    db.session.commit()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 788, in commit
    self.transaction.commit()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 384, in commit
    self._prepare_impl()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 364, in _prepare_impl
    self.session.flush()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1985, in flush
    self._flush(objects)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2103, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2067, in _flush
    flush_context.execute()
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 602, in _emit_insert_statements
    execute(statement, params)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 841, in execute
    return meth(self, multiparams, params)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 938, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1070, in _execute_context
    context)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1271, in _handle_dbapi_exception
    exc_info
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1063, in _execute_context
    context)
  File "/Users/eduaalva/Documents/Lab_Database_Project/savbu_database/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
InterfaceError: (InterfaceError) Error binding parameter 11 - probably unsupported type. u'INSERT INTO parts ("PO", "PR", part, project_name, requestor, supplier, supplier_contact, item_description, "CPN", "PID", manufacturer_part_num, submit_date, tracking, status, checkout_date, return_date, times_used, current_user, current_project) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' (u'23987', u'239847', u'DIMMs', u'Candlestick', u'eduaalva', u'HYNIX', u"'Roy Han' <roy.han@us.skhynix.com>", u'intel cpu', u'osinfroi', u'249987', u'soin24987', [u'04/17/2015'], u'23487', u'Available', None, None, 0, None, None)
2015-04-16 17:36:30,365 INFO: savbu-inventory startup [in /Users/eduaalva/Documents/Lab_Database_Project/savbu_database/app/__init__.py:42]
